var files =
[
    [ "abstracthttpserverrequesthandler.h", "abstracthttpserverrequesthandler_8h_source.html", null ],
    [ "abstracthttpserverrequesthandlerfactory.h", "abstracthttpserverrequesthandlerfactory_8h_source.html", null ],
    [ "abstracthttpupgradehandler.h", "abstracthttpupgradehandler_8h_source.html", null ],
    [ "abstractmessagesocket.h", "abstractmessagesocket_8h_source.html", null ],
    [ "headers.h", "headers_8h_source.html", null ],
    [ "httpfileserver.h", "httpfileserver_8h_source.html", null ],
    [ "httppluginserver.h", "httppluginserver_8h_source.html", null ],
    [ "httpserver.h", "httpserver_8h_source.html", null ],
    [ "httpserverrequest.h", "httpserverrequest_8h_source.html", null ],
    [ "httpserverrequestrouter.h", "httpserverrequestrouter_8h_source.html", null ],
    [ "httpserverresponse.h", "httpserverresponse_8h_source.html", null ],
    [ "httpsserver.h", "httpsserver_8h_source.html", null ],
    [ "httpupgraderouter.h", "httpupgraderouter_8h_source.html", null ],
    [ "ibytearray.h", "ibytearray_8h_source.html", null ],
    [ "main.h", "main_8h_source.html", null ],
    [ "pluginsystem.h", "pluginsystem_8h_source.html", null ],
    [ "querystring.h", "querystring_8h_source.html", null ],
    [ "safe-signal.h", "safe-signal_8h_source.html", null ],
    [ "session.h", "session_8h_source.html", null ],
    [ "sessionsettings.h", "sessionsettings_8h_source.html", null ],
    [ "sessionstore.h", "sessionstore_8h_source.html", null ],
    [ "simplesessionstore.h", "simplesessionstore_8h_source.html", null ],
    [ "tufao_global.h", "tufao__global_8h_source.html", null ],
    [ "url.h", "url_8h_source.html", null ],
    [ "urlrewriterhandler.h", "urlrewriterhandler_8h_source.html", null ],
    [ "websocket.h", "websocket_8h_source.html", null ]
];