/*  This file is part of the Tufão project
    Copyright (C) 2012 Vinícius dos Santos Oliveira <vini.ipsmaker@gmail.com>

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 3 of the License, or (at your option) any
    later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef TUFAO_ABSTRACTHTTPSERVERREQUESTHANDLER_H
#define TUFAO_ABSTRACTHTTPSERVERREQUESTHANDLER_H

#include "tufao_global.h"
#include <QtCore/QObject>
#include <QtCore/QStringList>

namespace Tufao {

class HttpServerRequest;
class HttpServerResponse;

/*!
  This class provides an interface for HttpServerRequest handlers.

  \since
  0.3
  */
class TUFAO_EXPORT AbstractHttpServerRequestHandler: public QObject
{
    Q_OBJECT
public:
    /*!
      Constructs an AbstractHttpServerRequestHandler object.
      */
    explicit AbstractHttpServerRequestHandler(QObject *parent = 0);

public slots:
    /*!
      Handles the \p request using the \p response object.

      \param args A list of options that may be used by the handler. The
      HttpServerRequestRouter class uses this argument to send the captured
      texts in the regex pattern.

      \retval true
      If the handler has responded to the request.

      \retval false
      If the requested page can't be generated by this handler. The connection
      should remain open and the \p response object shouldn't be used, leaving
      the response free to be used by other handlers in the chain.
      */
    virtual bool handleRequest(Tufao::HttpServerRequest *request,
                               Tufao::HttpServerResponse *response,
                               const QStringList &args = QStringList()) = 0;
};

} // namespace Tufao

#endif // TUFAO_ABSTRACTHTTPREQUESTHANDLER_H
