/*
  Copyright (c) 2012 Vinícius dos Santos Oliveira

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in all
  copies or substantial portions of the Software.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
  SOFTWARE.
  */

#ifndef TUFAO_HTTPPLUGINSERVER_H
#define TUFAO_HTTPPLUGINSERVER_H

#include "abstracthttpserverrequesthandler.h"

namespace Tufao {

/*!
  This class provides a plugin-based request handler. If you need to change the
  running server code at runtime, then this class is made for you.

  This class maintain its own HttpServerRequestRouter and a list of request
  handlers generated by the plugins to serve requests.

  The main problem solved by a plugin-based server is to store its configuration
  out of the code. This means that the server will need to reload the config
  when appropriate. There are several approaches to solve the problem, but none
  of them can be applied in every case, so this class is designed to work in
  every case by adding a little of effort to you. When the aimed event is
  triggered, call the reloadConfig slot and the configuration will be reloaded.

  To change its configuration file, use the tool shipped with Tufão.

  \sa
  AbstractHttpServerRequestHandlerFactory to implement your plugins.

  \since
  0.3
  */
class TUFAO_EXPORT HttpPluginServer : public AbstractHttpServerRequestHandler
{
    Q_OBJECT
public:
    /*!
      Constructs a HttpPluginServer object.

      \p parent is passed to the QObject constructor.

      \p configFile is used as configuration file.
      */
    explicit HttpPluginServer(const QString &configFile = QString(),
                              QObject *parent = 0);

    /*!
      Destroys the object.
      */
    ~HttpPluginServer();

    /*!
      Set the configuration file used to handle requests.

      Call this function will reload the configuration.

      \sa
      config
      */
    void setConfig(const QString &file);

    /*!
      Return the current used configuration file. This file is used to handle
      requests, loading the appropriate plugins, generating actual handlers and
      mapping them to the rules described in this file.
      */
    QString config() const;

public slots:
    /*!
      Handle the request using the loaded plugins and rules.
      */
    bool handleRequest(Tufao::HttpServerRequest *request,
                       Tufao::HttpServerResponse *response,
                       const QStringList &args = QStringList());

    /*!
      Clear all previous mappings and reload all rules and plugins.

      Call this function after change the configuration file to the changes take
      effect.
      */
    void reloadConfig();

private:
    void clear();

    struct Priv;
    Priv *priv;
};

} // namespace Tufao

#endif // TUFAO_HTTPPLUGINSERVER_H
